class classes.PDF.Components.CharacterSet.Sets.DelimiterCharacters:
    def public static property LP       as int init 0x28 no-undo get. // (
    def public static property RP       as int init 0x29 no-undo get. // )
    def public static property LTS      as int init 0x3c no-undo get. // <
    def public static property GTS      as int init 0x3e no-undo get. // >
    def public static property LSB      as int init 0x5b no-undo get. // [
    def public static property RSB      as int init 0x5d no-undo get. // ]
    def public static property LCB      as int init 0x7b no-undo get. // {
    def public static property RCB      as int init 0x7d no-undo get. // }
    def public static property SOLIDUS  as int init 0x2f no-undo get. // /
    def public static property RSOLIDUS as int init 0x5c no-undo get. // \
    def public static property PS       as int init 0x25 no-undo get. // %
end class.
